# NumPy package.

## Overview

The `numpy` package implements a multi-dimensional array type (`ndarray`) with set of methods and functions. The array type is implemented in C programming langugage and numerical optimizations as vectorization is used to speed up the code. 

Sometimes it is much faster to do a computation with `numpy` if the size of the array is large but generally `numpy` doesn't magicaly speedup your code. Before you start to change every code you had written to this day, remember that often a simple types and functions from `math` and `statistics` packages from standard library are good enough.

> We should forget about small efficiencies, say about 97% of the time: __premature optimization is the root of all evil.__<br>
> &mdash; D. Knuth in [_Structured Programming With Go To Statements_](https://pic.plover.com/knuth-GOTO.pdf)

The `numpy` package is usually abreviated as `np` when imported. You wiil see this in many examples and tutorials and we will stick with this convetion in all the examples.

In [ ]:
import numpy as np

## The 1-dimensional array

In [ ]:
data = np.array([1, 2, 3])
type(data)

In [ ]:
data.ndim

The shape property returns the tuple with dimensions for each axis. In our example the tuple has only one element because we created a one dimensioanl array with one axis and the dimension this axis is three.

In [ ]:
data.shape

In [ ]:
data = np.array([1, 2, 3, 4, 5])

In [ ]:
data.ndim

In [ ]:
data.shape

In [ ]:
#help(data)

We will create a two dimensioanl arrar which implies that it has a two axis.

In [ ]:
data = np.array([[1, 2]])

In [ ]:
data.ndim

In [ ]:
data.shape

## The 2-dimensional data

## The 3-dimensional data

## The N-dimensional data

# Přebrat

In [ ]:
# Modify the elements of a np 2D- array at specific locations without for loop.

# - Jak vytvořit kopii pole
# - Jak změnit prvek pole

u = np.array([1, 2, 3])
v = np.array([1, 2, 3])

print(
(u + v),
(u - v),
(u * v),
(u ** v),
)

# -----------------------------------------------------------------------------
# Vytvoř 1-dimenzionálního pole se zadanými hodnotami.
# -----------------------------------------------------------------------------

a = [11,12,21,22]
print(a)
print(len(a))

## Vytvořeni více-dimenzionálního pole

# -----------------------------------------------------------------------------
# Vytvoř 2-dimenzionálního pole kopírováním prvků zadaného sekvence.
# -----------------------------------------------------------------------------

b1 = np.array( [1, 2, 3] ) # list
b2 = np.array( (1, 2, 3) ) # tuple
b3 = np.array( {1, 2, 3} ) # set

print(b1)
print(b2)
print(b3)


# Vytvoř 2D pole kopírováním prvků zadaného 1D pole.
c = np.array(a).reshape(2,2)

print(c)

# Vytvoř 2D pole generováním (komprehenzí)
a = np.array([[True for j in range(3)] for i in range(3)])
print(a)

a = np.array([True] * 9).reshape(3, 3)
print(a)


# -----------------------------------------------------------------------------

# Skalární součin
(u @ v)

result = np.dot(
	np.array([1, 2, 3]), 
	np.array([1, 2, 3])
	)

# Jak spočíst skalární součin. 

A = [1, 2, 3]
B = [1, 2, 3]

# 1
from operator import mul
sum(map(mul, A, B))

# 2
sum([i*j for (i, j) in zip(A, B)])

# 5
scalar_product = lambda X, Y: sum(map(lambda x, y: x * y, X, Y))

In [3]:
np.arange(2, 8, 1)

array([2, 3, 4, 5, 6, 7])

In [4]:
5 * np.ones((6, 6))

array([[5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.]])

In [5]:
a = np.array([1, 2, 3, 5, 8])
a

array([1, 2, 3, 5, 8])

In [6]:
a = a + 1
a

array([2, 3, 4, 6, 9])

In [7]:
a[1]

3

In [1]:
import numpy as np
a = np.array([1, 2, 3, 5, 8])
b = np.array([0, 3, 4, 2, 1])
c = a + b
c = c * a

In [2]:
c[2]

21

In [8]:
e = np.array([[1, 2, 3], [0, 1, 4]]) # Počet prvků = 6

In [9]:
e.size

6

In [10]:
f = np.array([
    [0, 1, 2], 
    [3, 4, 5]
])
s = f.sum(axis=1)
s

array([ 3, 12])

In [22]:
g = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
np.ones_like(g)

array([[1, 1, 1],
       [1, 1, 1]])

In [24]:
True * np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.repeat(True, 9).reshape(3,3)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [28]:
np.reshape(9 * [True], (3,3))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [26]:
#today = dt.date.today()
#print(f'Today date: {today}')
#print(f'Before three days date: {today - dt.timedelta(days=3)}')
#print(f'After three days date: {today + dt.timedelta(days=3)}')

In [27]:
# Create a boolean (True/False) mask.
# date_mask = (dates > dt.date(1999, 12, 31)) & (dates < dt.date(2005, 1, 1)) #.dtype(int)

# Boolean (True/False) mask
# -------------------------
# The mask is used to select values with an index  which matches a `True` in the mask e.g
# data = np.array([_ for _ in 'abcdef'])
# mask = np.array([True, False, True, False, True, False])
# data[mask]
# The result is ['a', 'c', 'e']

# Integer (index) mask
# --------------------
# The mask is used to select values with an index  which matches a `True` in the mask e.g
# data = np.array([_ for _ in 'abcdef'])
# mask = np.array([0, 2, 4])
# data[mask]
# The result is ['a', 'c', 'e']

# selected_days = dates[date_mask]

# print(f'First day: {selected_days[0]} Last day: {selected_days[-1]}')

In [28]:
# fig, ax = plt.subplots(figsize=(16, 4))

# ax.set_title('Prague daily average temperature for selected days')
# ax.set_xlabel('date')
# ax.set_ylabel('Daily average')

# ax.plot(selected_days, t_avg[date_mask])